version: '3'

services:
  scheduler:
    image: spiside/luigi:latest
    container_name: scheduler
    ports:
    - 8082:8082

  db:
    image: mysql
    restart: always
    container_name: db
    ports:
    - 3306:3306
    volumes:
    - ./db:/db
    command: mysqld --init-file="/db/init.sql"
    environment:
      MYSQL_DATABASE: links
      MYSQL_USER: linker
      MYSQL_PASSWORD: linkerpassword
      MYSQL_ROOT_PASSWORD: password

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
    - 8080:8080
