version: '3.1'

services:
  scheduler:
    image: spiside/luigi:latest
    ports:
    - 8082:8082
    depends_on:
    - db

  db:
    image: mysql
    restart: always
    volumes:
    - ./db:/db
    command: mysqld --init-file="/db/init.sql"
    environment:
      MYSQL_DATABASE: links
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
